after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]

    alt-shift-space = 'close --quit-if-last-window'

    alt-shift-f = 'focus --boundaries-action wrap-around-the-workspace right'
    alt-shift-d = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-shift-s = 'workspace 1'
    alt-shift-a = 'workspace 2'

    alt-shift-r = 'move-node-to-workspace 2'
    alt-shift-e = 'move-node-to-workspace 1'
    alt-shift-w = 'layout accordion horizontal vertical'
    alt-shift-q = 'layout tiles horizontal vertical'

    alt-shift-v = 'resize smart -50'
    alt-shift-c = 'resize smart +50'
