        mm_ru_a: mod_morph_ru_a {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_a>, <&m_ru_a_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_be: mod_morph_ru_be {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_be>, <&m_ru_be_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ve: mod_morph_ru_ve {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ve>, <&m_ru_ve_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ge: mod_morph_ru_ge {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ge>, <&m_ru_ge_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_de: mod_morph_ru_de {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_de>, <&m_ru_de_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ye: mod_morph_ru_ye {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ye>, <&m_ru_ye_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_yo: mod_morph_ru_yo {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_yo>, <&m_ru_yo_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_zhe: mod_morph_ru_zhe {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_zhe>, <&m_ru_zhe_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ze: mod_morph_ru_ze {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ze>, <&m_ru_ze_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_i: mod_morph_ru_i {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_i>, <&m_ru_i_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_short_i: mod_morph_ru_short_i {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_short_i>, <&m_ru_short_i_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ka: mod_morph_ru_ka {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ka>, <&m_ru_ka_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_el: mod_morph_ru_el {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_el>, <&m_ru_el_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_em: mod_morph_ru_em {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_em>, <&m_ru_em_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_en: mod_morph_ru_en {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_en>, <&m_ru_en_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_o: mod_morph_ru_o {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_o>, <&m_ru_o_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_pe: mod_morph_ru_pe {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_pe>, <&m_ru_pe_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_er: mod_morph_ru_er {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_er>, <&m_ru_er_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_es: mod_morph_ru_es {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_es>, <&m_ru_es_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_te: mod_morph_ru_te {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_te>, <&m_ru_te_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_u: mod_morph_ru_u {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_u>, <&m_ru_u_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ef: mod_morph_ru_ef {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ef>, <&m_ru_ef_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ha: mod_morph_ru_ha {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ha>, <&m_ru_ha_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_tse: mod_morph_ru_tse {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_tse>, <&m_ru_tse_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_che: mod_morph_ru_che {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_che>, <&m_ru_che_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_sha: mod_morph_ru_sha {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_sha>, <&m_ru_sha_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_shcha: mod_morph_ru_shcha {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_shcha>, <&m_ru_shcha_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_hard: mod_morph_ru_hard {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_hard>, <&m_ru_hard_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_yery: mod_morph_ru_yery {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_yery>, <&m_ru_yery_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_soft: mod_morph_ru_soft {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_soft>, <&m_ru_soft_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_e: mod_morph_ru_e {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_e>, <&m_ru_e_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_yu: mod_morph_ru_yu {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_yu>, <&m_ru_yu_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_ya: mod_morph_ru_ya {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&m_ru_ya>, <&m_ru_ya_u>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_dot: mod_morph_ru_dot {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&kp DOT>, <&kp SEMI>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        mm_ru_comma: mod_morph_ru_comma {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&kp COMMA>, <&m_ru_mdash>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
        };
        ru_tog: ru_layer_toggle {
            compatible = "zmk,behavior-hold-tap";
            label = "RU_TOGGLE";
            #binding-cells = <2>;
            flavor = "tap-preferred";
            tapping-term-ms = <200>;
            bindings = <&kp>, <&to>;
        };
