name: Build Glove80 firmware

on:
  push:
    paths:
      - "glove80-zmk-config/**"
      - ".github/workflows/glove80.yml"
  pull_request:
    paths:
      - "glove80-zmk-config/**"
      - ".github/workflows/glove80.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: glove80-zmk-config
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: glove80-zmk-config/src

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - uses: cachix/cachix-action@v14
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true

      - name: Build Glove80 combined firmware
        run: nix-build config -o combined

      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: glove80.uf2
          path: glove80-zmk-config/glove80.uf2
